
---
apiVersion: v1
kind: Service
metadata:
  name: ruleta_rusa-client
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
      app: random-memes-front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruleta_rusa-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruleta_rusa-client
  template:
    metadata:
      labels:
        app: ruleta_rusa-client
    spec:
      containers:
      - name: ruleta_rusa-client
        image: carlospmve/ruleta_rusa-client
        ports:
        - containerPort: 5000
